### ISSUE TITLE
Migrate to eslint from tslint

### ISSUE THREAD

**Issue by iamtraction** [AwesomeDocs/AwesomeDocs#13]
#### Why?
A while back `eslint` integrated the parser from `tslint` and now supports linting TypeScript. And therefore `tslint` is now deprecated. 

#### Resources
ESLint - https://eslint.org/
Reference ESLint config. for TypeScript - https://github.com/TheBastionBot/Locke/blob/master/.eslintrc.yml

**Comment by yogmel** [comment]
Hi @k3rn31p4nic 
can I work on this task?
So Eslint should be integrated/implemented and we should remove tslint, right?

**Comment by iamtraction** [comment]
>  can I work on this task?

Yes, absolutely.

>  So Eslint should be integrated/implemented and we should remove tslint, right?

Yeah, correct.
