### ISSUE TITLE
Improvements : Switch monospaced font to JetBrains Mono and Add possibility to switch themes

### ISSUE THREAD

**Issue by yiss** [AwesomeDocs/AwesomeDocs#17]
Hi I like this project a lot documentation is very sleek and the website is very speedy. I would like to make some improvements if you want I can try make this changes myself :)

**Comment by iamtraction** [comment]
Feel free to open PRs if you've something in mind!

**Comment by yiss** [comment]
@k3rn31p4nic Thank you I'm working on it. BTW what SVG Icons did you use in your code ?

**Comment by iamtraction** [comment]
I use `react-icons`, specifically Feather Icons and iOS version of Ionicons. It's already included and can be accessed from `react-icons/fi` and `react-icons/io` respectively.
